<?php

namespace Northwind\Proxy\__CG__\Northwind\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Supplier extends \Northwind\Entity\Supplier implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setCompanyname($companyname)
    {
        $this->__load();
        return parent::setCompanyname($companyname);
    }

    public function getCompanyname()
    {
        $this->__load();
        return parent::getCompanyname();
    }

    public function setContactname($contactname)
    {
        $this->__load();
        return parent::setContactname($contactname);
    }

    public function getContactname()
    {
        $this->__load();
        return parent::getContactname();
    }

    public function setContacttitle($contacttitle)
    {
        $this->__load();
        return parent::setContacttitle($contacttitle);
    }

    public function getContacttitle()
    {
        $this->__load();
        return parent::getContacttitle();
    }

    public function setAddress($address)
    {
        $this->__load();
        return parent::setAddress($address);
    }

    public function getAddress()
    {
        $this->__load();
        return parent::getAddress();
    }

    public function setCity($city)
    {
        $this->__load();
        return parent::setCity($city);
    }

    public function getCity()
    {
        $this->__load();
        return parent::getCity();
    }

    public function setRegion($region)
    {
        $this->__load();
        return parent::setRegion($region);
    }

    public function getRegion()
    {
        $this->__load();
        return parent::getRegion();
    }

    public function setPostalcode($postalcode)
    {
        $this->__load();
        return parent::setPostalcode($postalcode);
    }

    public function getPostalcode()
    {
        $this->__load();
        return parent::getPostalcode();
    }

    public function setCountry($country)
    {
        $this->__load();
        return parent::setCountry($country);
    }

    public function getCountry()
    {
        $this->__load();
        return parent::getCountry();
    }

    public function setPhone($phone)
    {
        $this->__load();
        return parent::setPhone($phone);
    }

    public function getPhone()
    {
        $this->__load();
        return parent::getPhone();
    }

    public function setFax($fax)
    {
        $this->__load();
        return parent::setFax($fax);
    }

    public function getFax()
    {
        $this->__load();
        return parent::getFax();
    }

    public function setHomepage($homepage)
    {
        $this->__load();
        return parent::setHomepage($homepage);
    }

    public function getHomepage()
    {
        $this->__load();
        return parent::getHomepage();
    }

    public function getSupplierid()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["supplierid"];
        }
        $this->__load();
        return parent::getSupplierid();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'companyname', 'contactname', 'contacttitle', 'address', 'city', 'region', 'postalcode', 'country', 'phone', 'fax', 'homepage', 'supplierid');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}